@host = https://localhost
@port = 7115
@token = CfDJ8BC8kxE1x5pDqTdZom6VR7m7FhAcGPX0iT9OA9qekCrH70kXVny5SgM_0Ksg8B7M2f2-cyUbG37nSX-R7QH5ekQMysenT1ofkAtOxwqq6sTujcBJVNIdrWoZK5_VcwY-Qg3rgZB91b_h-AadGv8GV0MkOMe5_UbXzGwKtv-AuaIhP80jSmkEGZU6VSrMJVuPSzQWmCADqVZVk-dYm2hKPOZr2qZTpXFWlC-1UvLGVAmwDt4dUJ11Ku3s6-wYK0GHzkMwjR2JhGHVYDTrwG1qNOVLyq16PECaVBjHWv8yH1WXWR08Kl6rviX2eKeDS0FOG_Z6khfhLrSCca7X5ggtvSffETqF_rxweeIiWBsLMij5vPEXgfyIfFcy0h16Q8hShh9cv42yCjryxwc585zCU9KXgyIHaXy11ZntWtxSQYNmtHgaY2zZ3fpLqFHNz8tN-1oihzgRmlbXtr_fIRkI5P49kn-MutfNvFdu6QGl2DlZ9SYU8_P-f1W_vcsH7UDew2iloI8Ps9PAGwhl0gbdeTetiuotrO6AsMLfiusM9pAGGb4VoCSshXg17ycRjbLu-rDDdBlPQSsys84tyrM7_2OwnDV_o53Fbw94Kv_3DWEZbHKCWL9sR5lfrFyR2GVIPjvVbVHpJ7bdglLYEUXsVJWvv3lMo6-uD462y6Q1waURj5ZND9pXDUsgUtdTEyLd5hmhDXHiZlLYRqUzA5QyIODCBeNwdlK_VRDYr7bPAWRy2IIpjUQXNNJui6soagDngyYtacGEoaE1O962iatOuhI
@Restaurants.API_HostAddress = https://localhost:7115


GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1
Authorization: Bearer {{token}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes
Authorization: Bearer {{token}}
###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/50/dishes

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes/2

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json
{
      "Name": "Owner2 restaurant5",
      "Description": "A cozy restaurant serving a variety of delicious dishes.",
      "Category": "Indian",
      "HasDelivery": true,
      "ContactEmail": "info@test.com",
      "ContactNumber": "555-1234",
      "City": "New York",
      "Street": "123 Main Street",
      "PostalCode": "10-010"
}

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/{restaurantId}
Content-Type: application/json

{
  "Name": "Sample Patch",
  "Description": "A cozy restaurant serving a variety of delicious dishes.",
  "HasDelivery": true
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes
Content-Type: application/json

{
  "Name": "Pasta",
  "Description": "Delicious pasta with tomato sauce",
  "Price": 25,
  "KiloCalories": 15
}

###

GET https://localhost:7115/api/restaurants/1/dishes/1009

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json
{
    "email": "User@test.com",
    "password": "Password1!"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json
{
    "email": "test@test.com",
    "password": "Password1!"
}

###

PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Authorization: Bearer {{token}}
Content-Type: application/json
{
    "Nationality": "Egypt",
    "DateOfBirth": "2002-01-01"
}