@host = https://localhost
@port = 7115
@token = CfDJ8BC8kxE1x5pDqTdZom6VR7lnsRnhE3GlqEgh2IXjzgrijlv793OdsfA1wEtc4a28Tv32oQqOb32BJzm53rADBcX1Z9b-i5vgS8RYGvCplBrHSW9xlndJ1pmacrRg_YeJNAULcXOFCeUKzp406oCa81zid8LWGhFrODC2FmiGG4-GBkKuAwo_-UtZHROn4NyKArC5kCJi3JahanOuT6DD0rgB2Wo5NwwttyAuOm-Ga8We5bFYGrnNXZLDGMNZVDQfProG18N2G9Qma2AeH357TS3zOyAfBjbu5kIbAPVy8WHR-XaCBpJYpMAFA7DEXJUt_G1k_atNRLXxyiEOYl3w5FyFS2gL7lSr_fqmbUqcnE4pgXsoOM3FjTtELAFvfBcgs-VOALIXrL9KqH6AknOMV7S754kGE9Fkp3ab0InW36tv_MFRRuLrlaSnkxY7n_1T6tARTI9gY3wzwUm1nbRw4Jg3QMwz5Sni3i1LlNlSQIoqDPsKOj1-pcJ4EWf37Gn4VFlmMgtMCS_9nLAqtLLxWwkbh30IMTL2RBsobj5OYzcWRLB_pIXUxoUJ8qt8FOlovkA8gWams1ij-c61zk-EVfrDpVsO3VjA-WC3c8gaaPYDhyQdfmt57-znY6DuIn2sTUe3YYZ5zUXbu8Fcph-FnPVvHNY-hmDv8YnmaK-mlNTykI5giI-r9REANILzFLCJDxjLYFvpY8h1oeyoORSLGc-gnzFpQSdvPy1sy7PiSckfL65VLqJb7Keb5dKphonL7kxhXmNnpQeVaeyXy9C7kBA
@Restaurants.API_HostAddress = https://localhost:7115


GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1
Authorization: Bearer {{token}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/50/dishes

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes/2

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json
{
      "Name": "Owner2 restaurant5",
      "Description": "A cozy restaurant serving a variety of delicious dishes.",
      "Category": "Indian",
      "HasDelivery": true,
      "ContactEmail": "info@test.com",
      "ContactNumber": "555-1234",
      "City": "New York",
      "Street": "123 Main Street",
      "PostalCode": "10-010"
}

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/{restaurantId}
Content-Type: application/json

{
  "Name": "Sample Patch",
  "Description": "A cozy restaurant serving a variety of delicious dishes.",
  "HasDelivery": true
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes
Content-Type: application/json

{
  "Name": "Pasta",
  "Description": "Delicious pasta with tomato sauce",
  "Price": 25,
  "KiloCalories": 15
}

###

GET https://localhost:7115/api/restaurants/1/dishes/1009

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json
{
    "email": "User@test.com",
    "password": "Password1!"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json
{
    "email": "test@test.com",
    "password": "Password1!"
}

###

PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Authorization: Bearer {{token}}
Content-Type: application/json
{
    "DateOfBirth": "2002-01-01",
    "Nationality": "French"
}